#!/usr/bin/env bash
# Generates one GPG signing key per identity defined in gpg/identities/*.sh,
# points the matching per-host git config file at it (commit/tag signing),
# and tries to register the public key with the matching CLI (gh/glab) if
# authenticated — otherwise prints it for you to paste in manually.
#
# Not run automatically by bootstrap.sh — generating a new signing identity
# is deliberate, run it yourself:
#   ./gpg/setup-gpg-keys.sh
#
# Safe to re-run: any identity that already has a matching secret key is left
# alone (its git config file is still rewritten to match, in case the
# fingerprint or routing changed).

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

mkdir -p "$HOME/.gnupg"
chmod 700 "$HOME/.gnupg"

for identity_file in ./identities/*.sh; do
    [ -e "$identity_file" ] || continue

    # Each identity file sets IDENTITY_NAME, IDENTITY_EMAIL, IDENTITY_UID,
    # IDENTITY_GITCONFIG_PATH, and optionally IDENTITY_REGISTER_CMD.
    unset IDENTITY_NAME IDENTITY_EMAIL IDENTITY_UID IDENTITY_GITCONFIG_PATH IDENTITY_REGISTER_CMD 2>/dev/null || true
    # shellcheck source=/dev/null
    source "$identity_file"

    echo "==> ${IDENTITY_NAME}"

    fingerprint="$(gpg --list-secret-keys --with-colons "$IDENTITY_EMAIL" 2>/dev/null \
        | awk -F: '/^fpr:/ {print $10; exit}')"

    if [ -n "$fingerprint" ]; then
        echo "    key already exists ($fingerprint), skipping generation."
    else
        gpg --quick-generate-key "$IDENTITY_UID" ed25519 sign 0
        fingerprint="$(gpg --list-secret-keys --with-colons "$IDENTITY_EMAIL" \
            | awk -F: '/^fpr:/ {print $10; exit}')"
    fi

    cat > "$IDENTITY_GITCONFIG_PATH" <<EOF
# Generated by gpg/setup-gpg-keys.sh (${IDENTITY_NAME}) — do not hand-edit,
# it gets overwritten on every run. Put your own tweaks in dot_gitconfig
# instead.
[user]
    signingkey = ${fingerprint}
[commit]
    gpgsign = true
[tag]
    gpgsign = true
EOF
    echo "    wrote ${IDENTITY_GITCONFIG_PATH}"

    if [ -n "${IDENTITY_REGISTER_CMD:-}" ] && eval "$IDENTITY_REGISTER_CMD"; then
        echo "    registered."
    else
        echo "    could not auto-register (CLI not installed/authenticated?). Add this manually:"
        echo ""
        gpg --armor --export "$IDENTITY_EMAIL"
        echo ""
    fi
done

echo "==> Done."
